language: r
sudo: false
cache: packages
dist: trusty

r_binary_packages:
  - covr

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
      env: R_CODECOV=true

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

r_check_args: "--as-cran --run-dontrun"

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: XjCNOufVyfFUl9MIW6Vh7d/lcInse0lM3Le/XAdOJLYMpqwGiVQjhbxcHU68uXSX2LmuraLA0PsXTq6Hw2ciNUFo5oqCdTkhTNRbk8S5mzZWupZzGR1JEdAtP3MlOQcRmeObzw35pEdJh4fmG7OPhq4vLCeh915oClmFYyoXBgk=
